### ISSUE TITLE
Can the above  chatbot be used for SAP ERP  also?

### ISSUE THREAD

**Issue by flash2007** [B1SA/smb-recast-bot#2]
Can the above chatbot be used for SAP ERP also?

**Comment by YatseaLi** [comment]
Hi Flash,

Not, the adapter is not yet in place for SAP ERP. Only SAP ByD and SAP Business One are supported through OData to its analytics content.

However, architecturally it is ERP-agnostic through loosely-coupled, which can easily be extended to support SAP ERP by having an abstraction layer for NLP to analytics mapping model, it just requires another mapping from the abstract analytics model to SAP ERP or SAP BW,  and another query generator to SAP ERP or SAP BW for its analytics content via OData through SAP Gateway. 

If you would like to implement it by yourself, please refer to this [manual](https://github.com/B1SA/smb-recast-bot/tree/master/server). Here list the general procedures.

1. ERP configuration for accessing the analytics content via OData:
please check this blog about https://blogs.sap.com/2019/02/19/how-to-do-odata-services-from-bex-query/
2.Add the new values of [system type](https://cai.tools.sap/yatseali/smb-recast-bot/train/entities/system_type) representing "SAP ERP" or "SAP BW" to the login-erp intent after you have forked the smb-recast-bot.
3.Add the mapping configuration of intent to semantics for SAP ERP/SAP BW in [intents_mapping.js ](https://github.com/B1SA/smb-recast-bot/blob/master/server/lib/config/intents_mapping.js)
3.Implement the OData query generator for SAP ERP/SAP BW. Please refer to the [B1QueryGenerator](https://github.com/B1SA/smb-recast-bot/blob/master/server/lib/b1/b1_query_generator.js) and [ByDQueryGenerator](https://github.com/B1SA/smb-recast-bot/blob/master/server/lib/byd/byd_query_generator.js)
4.Adapt the endpoint /webhooks/login and /webhooks/analytics for SAP ERP or SAP BW in [index.js](https://github.com/B1SA/smb-recast-bot/blob/master/server/index.js)

And your contribution is more than welcome. Please feel free to let me know if you need further clarity. Thanks.

Kind Regards, Yatsea

**Comment by flash2007** [comment]
ok thank you

**Comment by flash2007** [comment]
okay thank you
